version: '3'
services: 
    product-service:
        build: ./apipdf/
        volumes:
            - ./apipdf/:/usr/src/app/
        ports: 
            - 8686:8686
        environment: 
            PORT: 8686
            FLASK_DEBUG: 1
            grafana_domain: '34.133.152.106:3000'
        network_mode: host
